// <auto-generated />
using JPCadastro.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JPCadastro.Infra.Data.Migrations
{
    [DbContext(typeof(JPCadastroContext))]
    [Migration("20220509120057_AlunoInicial")]
    partial class AlunoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JPCadastro.Operacional.Entities.Aluno.AlunoEntity", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Cpf");

                    b.ToTable("TAB_Aluno", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
